# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 706)
        self.width=540
        self.height=706
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.watchList = QtWidgets.QTableWidget(self.centralwidget)
        self.watchList.setGeometry(QtCore.QRect(120, 120, 160, 211))
        self.watchList.setObjectName("watchList")
        self.watchList.setColumnCount(1)
        self.watchList.setRowCount(0)
        self.camList = QtWidgets.QTableWidget(self.centralwidget)
        self.camList.setGeometry(QtCore.QRect(120, 440, 160, 211))
        self.camList.setObjectName("camList")
        self.camList.setColumnCount(1)
        self.camList.setRowCount(10)
        self.camLabel = QtWidgets.QLabel(self.centralwidget)
        self.camLabel.setGeometry(QtCore.QRect(130, 395, 191, 30))
        self.camLabel.setStyleSheet("font: 12pt \"黑体\";")
        self.camLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.camLabel.setObjectName("camLabel")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 395, 30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/monitorMenu/拥有.png"))
        self.label_5.setObjectName("label_5")
        self.watchLabel = QtWidgets.QLabel(self.centralwidget)
        self.watchLabel.setStyleSheet("font: 12pt \"黑体\";")
        self.watchLabel.setGeometry(QtCore.QRect(130, 75, 191, 30))
        self.watchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.watchLabel.setObjectName("watchLabel")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 75, 30, 30))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/monitorMenu/眼睛.png"))
        self.label_4.setObjectName("label_4")
        self.add1 = QtWidgets.QPushButton(self.centralwidget)
        self.add1.setStyleSheet("font: 12pt \"黑体\";")
        self.add1.setGeometry(QtCore.QRect(350, 160, 91, 41))
        self.add1.setObjectName("add1")
        self.delete1 = QtWidgets.QPushButton(self.centralwidget)
        self.delete1.setStyleSheet("font: 12pt \"黑体\";")
        self.delete1.setGeometry(QtCore.QRect(350, 240, 91, 41))
        self.delete1.setObjectName("delete1")
        self.delete2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete2.setStyleSheet("font: 12pt \"黑体\";")
        self.delete2.setGeometry(QtCore.QRect(350, 560, 91, 41))
        self.delete2.setObjectName("delete2")

        self.share = QtWidgets.QPushButton(self.centralwidget)
        self.share.setStyleSheet("font: 12pt \"黑体\";")
        self.share.setGeometry(QtCore.QRect(350, 480, 91, 41))
        self.share.setObjectName("share")
        item = QtWidgets.QTableWidgetItem()
        self.camList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.camList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.camList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.watchList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.watchList.setHorizontalHeaderItem(1, item)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "监控编辑"))
        self.camLabel.setText(_translate("MainWindow", "我拥有的摄像头"))
        self.watchLabel.setText(_translate("MainWindow", "我可观看的摄像头"))
        self.add1.setText(_translate("MainWindow", "添加"))
        self.delete1.setText(_translate("MainWindow", "移除"))
        self.delete2.setText(_translate("MainWindow", "删除"))

        self.share.setText(_translate("MainWindow", "分享"))
        self.camList.horizontalHeaderItem(0).setText(_translate("MainWindow", "摄像头名"))
        self.watchList.horizontalHeaderItem(0).setText(_translate("MainWindow", "摄像头名"))

import resource.resource_rc



