# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.width=int(QApplication.desktop().screenGeometry().width()*0.28125)
        self.height=int(QApplication.desktop().screenGeometry().height()*0.5)
        Form.resize(self.width,self.height)
        self.userID = QtWidgets.QLineEdit(Form)
        self.userID.setGeometry(QtCore.QRect(int(200*self.width/488), int(190*self.height/435), int(171*self.width/488), int(31*self.height/435)))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.userID.setFont(font)
        self.userID.setObjectName("userID")
        self.userID.setClearButtonEnabled(True)
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(int(200*self.width/488), int(260*self.height/435), int(171*self.width/488), int(31*self.height/435)))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.userID_ = QtWidgets.QLabel(Form)
        self.userID_.setGeometry(QtCore.QRect(int(110*self.width/488), int(190*self.height/435), int(31*self.width/488), int(31*self.height/435)))
        self.userID_.setText("")
        self.userID_.setPixmap(QtGui.QPixmap(":/login/帐号.png"))
        self.userID_.setObjectName("userID_")
        self.password_ = QtWidgets.QLabel(Form)
        self.password_.setGeometry(QtCore.QRect(int(110*self.width/488), int(260*self.height/435), int(31*self.width/488), int(31*self.height/435)))
        self.password_.setText("")
        self.password_.setPixmap(QtGui.QPixmap(":/login/密码.png"))
        self.password_.setObjectName("password_")
        self.titlePic = QtWidgets.QLabel(Form)
        self.titlePic.setGeometry(QtCore.QRect(int(50*self.width/488), int(50*self.height/435), int(111*self.width/488), int(111*self.height/435)))
        self.titlePic.setText("")
        self.titlePic.setPixmap(QtGui.QPixmap(":/login/监控.png"))
        self.titlePic.setObjectName("titlePic")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(int(190*self.width/488), int(80*self.height/435), int(231*self.width/488), int(61*self.height/435)))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.id = QtWidgets.QLabel(Form)
        self.id.setGeometry(QtCore.QRect(int(150*self.width/488), int(190*self.height/435), int(41*self.width/488), int(31*self.height/435)))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.pwd = QtWidgets.QLabel(Form)
        self.pwd.setGeometry(QtCore.QRect(int(150*self.width/488), int(260*self.height/435), int(41*self.width/488), int(31*self.height/435)))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pwd.setFont(font)
        self.pwd.setObjectName("pwd")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(int(140 * self.width / 488), int(330 * self.height / 435), int(81 * self.width / 488), int(41 * self.height / 435)))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("pushButton")
        self.registerButton = QtWidgets.QPushButton(Form)
        self.registerButton.setGeometry(QtCore.QRect(int(260 * self.width / 488), int(330 * self.height / 435), int(81 * self.width / 488), int(41 * self.height / 435)))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录界面"))
        self.title.setText(_translate("Form", "智能监控系统"))
        self.id.setText(_translate("Form", "帐号"))
        self.pwd.setText(_translate("Form", "密码"))
        self.loginButton.setText(_translate("Form", "登录"))
        self.registerButton.setText(_translate("Form", "注册"))

import resource.resource_rc
