# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitorMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 384)
        self.width = 410
        self.height = 384
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.watchBox = QtWidgets.QComboBox(self.centralwidget)
        self.watchBox.setGeometry(QtCore.QRect(110, 151, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.watchBox.setFont(font)
        self.watchBox.setObjectName("watchBox")
        self.playWatch = QtWidgets.QPushButton(self.centralwidget)
        self.playWatch.setGeometry(QtCore.QRect(240, 151, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.playWatch.setFont(font)
        self.playWatch.setObjectName("playWatch")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 239, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.camBox = QtWidgets.QComboBox(self.centralwidget)
        self.camBox.setGeometry(QtCore.QRect(110, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.camBox.setFont(font)
        self.camBox.setObjectName("camBox")
        self.playCam = QtWidgets.QPushButton(self.centralwidget)
        self.playCam.setGeometry(QtCore.QRect(240, 280, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.playCam.setFont(font)
        self.playCam.setObjectName("playCam")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 110, 30, 30))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/monitorMenu/眼睛.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 240, 30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/monitorMenu/拥有.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 50, 30, 30))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/monitorMenu/监控(小).png"))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "摄像头总览"))
        self.label.setText(_translate("MainWindow", "摄像头总览"))
        self.playWatch.setText(_translate("MainWindow", "播放"))
        self.label_2.setText(_translate("MainWindow", "可观看"))
        self.label_3.setText(_translate("MainWindow", "拥有"))
        self.playCam.setText(_translate("MainWindow", "播放"))
        # self.back.setText(_translate("MainWindow", "返回"))

import resource.resource_rc
