# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'share.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 560)
        self.width=490
        self.height=560
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cam_id = QtWidgets.QComboBox(self.centralwidget)
        self.cam_id.setGeometry(QtCore.QRect(190, 140, 120, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.cam_id.setFont(font)
        self.cam_id.setObjectName("cam_id")
        self.watcherList = QtWidgets.QTableWidget(self.centralwidget)
        self.watcherList.setGeometry(QtCore.QRect(160, 200, 170, 211))
        self.watcherList.setObjectName("watcherList")
        self.watcherList.setColumnCount(1)
        self.watcherList.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 90, 230, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.queryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.queryBtn.setGeometry(QtCore.QRect(330, 138, 70, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.queryBtn.setFont(font)
        self.queryBtn.setObjectName("queryBtn")
        self.user_id_input = QtWidgets.QLineEdit(self.centralwidget)
        self.user_id_input.setGeometry(QtCore.QRect(220, 480, 90, 31))
        self.user_id_input.setObjectName("user_id")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 470, 141, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 430, 320, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.removeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.removeBtn.setGeometry(QtCore.QRect(330, 478, 70, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.removeBtn.setFont(font)
        self.removeBtn.setObjectName("removeBtn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        item = QtWidgets.QTableWidgetItem()
        self.watcherList.setHorizontalHeaderItem(0, item)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "我的分享"))
        self.label.setText(_translate("MainWindow", "分享摄像头详情"))
        self.queryBtn.setText(_translate("MainWindow", "查询"))
        self.label_2.setText(_translate("MainWindow", "请输入移除当前\n"
"摄像头的用户名:"))
        self.removeBtn.setText(_translate("MainWindow", "移除"))
        self.label_3.setText(_translate("MainWindow", "摄像头："))
        self.label_4.setText(_translate("MainWindow", "当前摄像头：无"))
        self.watcherList.horizontalHeaderItem(0).setText(_translate("MainWindow", "用户名"))
